INSERT INTO
    players (
        username,
        rating,
        country_code,
        total_games,
        wins,
        losses,
        draws,
        last_active_at
    )
VALUES
    (
        'magnus',
        2880,
        'NO',
        1200,
        900,
        200,
        100,
        CURRENT_TIMESTAMP
    ),
    (
        'hikaru',
        2850,
        'US',
        1500,
        1000,
        350,
        150,
        CURRENT_TIMESTAMP
    ),
    (
        'alireza',
        2810,
        'FR',
        900,
        600,
        200,
        100,
        CURRENT_TIMESTAMP
    ),
    (
        'pragg',
        2785,
        'IN',
        800,
        520,
        190,
        90,
        CURRENT_TIMESTAMP
    ),
    (
        'muntaha',
        1500,
        'BD',
        200,
        90,
        90,
        20,
        CURRENT_TIMESTAMP
    ),
    (
        'tania',
        1750,
        'BD',
        350,
        180,
        130,
        40,
        CURRENT_TIMESTAMP
    ),
    (
        'nepomniachtchi',
        2790,
        'RU',
        1100,
        750,
        250,
        100,
        CURRENT_TIMESTAMP
    ),
    (
        'fabiano',
        2820,
        'US',
        1300,
        880,
        300,
        120,
        CURRENT_TIMESTAMP
    ),
    (
        'wesley',
        2760,
        'US',
        1000,
        650,
        250,
        100,
        CURRENT_TIMESTAMP
    ),
    (
        'ding',
        2805,
        'CN',
        1150,
        780,
        250,
        120,
        CURRENT_TIMESTAMP
    );

INSERT INTO
    games (
        white_player_id,
        black_player_id,
        result,
        rated,
        moves,
        started_at,
        ended_at,
        termination
    )
VALUES
    (
        1,
        2,
        'WHITE',
        TRUE,
        42,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'CHECKMATE'
    ),
    (
        2,
        1,
        'DRAW',
        TRUE,
        85,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'STALEMATE'
    ),
    (
        5,
        6,
        'BLACK',
        TRUE,
        60,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'TIME'
    ),
    (
        6,
        5,
        'WHITE',
        TRUE,
        34,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'RESIGN'
    ),
    (
        3,
        4,
        'WHITE',
        TRUE,
        51,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'CHECKMATE'
    ),
    (
        4,
        3,
        'BLACK',
        TRUE,
        44,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'RESIGN'
    ),
    (
        8,
        9,
        'DRAW',
        TRUE,
        72,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'THREEFOLD'
    ),
    (
        9,
        8,
        'BLACK',
        TRUE,
        38,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'TIME'
    ),
    (
        10,
        1,
        'WHITE',
        TRUE,
        57,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'CHECKMATE'
    ),
    (
        7,
        10,
        'BLACK',
        TRUE,
        49,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'RESIGN'
    );